{
 "title": "Aggregated metrics board",
 "time": { "from": "2018-11-30T11:49:05.995Z", "to": "2018-11-30T13:49:05.995Z" },
 "panels": [
  {
   "title": "System load average (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "system.load.average.1m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "system.cpu.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min, Max and Mean  CPU Usage Across Apps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "process.cpu.usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "process.cpu.usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "process.cpu.usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average vs Max JVM Memory Across all Apps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jvm.memory.used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jvm.memory.max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}