{
 "title": "Interact platform metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application Health",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "collaboration-service-app health",
     "measurement": "health",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "collaboration-service-app" }
     ]
    },
    {
     "alias": "collaboration-transformer-app health",
     "measurement": "health",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "collaboration-transformer-app" }
     ]
    },
    {
     "alias": "collaboration-ui-app health",
     "measurement": "health",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "collaboration-ui-app" }
     ]
    },
    {
     "alias": "collaboration-command-consumer-app health",
     "measurement": "health",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "application",
       "operator": "=",
       "value": "notification-command-consumer-app"
      }
     ]
    },
    {
     "alias": "notification-indexer-app health",
     "measurement": "health",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "notification-indexer-app" }
     ]
    },
    {
     "alias": "notification-service-app health",
     "measurement": "health",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "notification-service-app" }
     ]
    },
    {
     "alias": "notification-ui-app health",
     "measurement": "health",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "notification-ui-app" }
     ]
    },
    {
     "alias": "task-indexer-app health",
     "measurement": "health",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "task-indexer-app" }
     ]
    },
    {
     "alias": "task-service-app health",
     "measurement": "health",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "task-service-app" }
     ]
    },
    {
     "alias": "task-ui-app health",
     "measurement": "health",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "task-ui-app" }
     ]
    },
    {
     "alias": "notification-command-consumer-app health",
     "measurement": "health",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "application",
       "operator": "=",
       "value": "notification-command-consumer-app"
      }
     ]
    },
    {
     "alias": "task-command-consumer-app health",
     "measurement": "health",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "task-command-consumer-app" }
     ]
    }
   ]
  },
  {
   "title": "Infrastructure health",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 1 },
   "format": "short",
   "valueName": "current",
   "content": "graph TD\ncollaboration-tool --> message-bus((message-bus))\ndynamic-case[dynamic-case] --> message-bus\ncollaboration-transformer-app[collaboration-transformer-app] --> message-bus\ncollaboration-transformer-app[collaboration-transformer-app] --> redis((redis))\ntask-command-consumer-app[task-command-consumer-app] --> message-bus\nnotification-command-consumer-app[notification-command-consumer-app] --> message-bus\ntask-indexer-app[task-indexer-app] --> message-bus \nnotification-indexer-app[notification-indexer-app] --> message-bus \ntask-indexer-app --> elasticsearch((elasticsearch))\nelasticsearch --> task-service-app \nnotification-indexer-app --> elasticsearch\nelasticsearch --> notification-service-app   ",
   "targets": [
    {
     "alias": "collaboration-transformer-app",
     "measurement": "health",
     "query": "SELECT \"value\" FROM \"health\" WHERE (\"application\" = 'collaboration-transformer-app') AND $timeFilter AND time > now() - 2m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "collaboration-transformer-app" }
     ]
    },
    {
     "alias": "notification-command-consumer-app",
     "measurement": "health",
     "query": "SELECT \"value\" FROM \"health\" WHERE (\"application\" = 'notification-command-consumer-app') AND $timeFilter AND time > now() - 2m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "application",
       "operator": "=",
       "value": "notification-command-consumer-app"
      }
     ]
    },
    {
     "alias": "task-command-consumer-app",
     "measurement": "health",
     "query": "SELECT \"value\" FROM \"health\" WHERE (\"application\" = 'task-command-consumer-app') AND $timeFilter AND time > now() - 2m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "task-command-consumer-app" }
     ]
    },
    {
     "alias": "notification-indexer-app",
     "measurement": "health",
     "query": "SELECT \"value\" FROM \"health\" WHERE (\"application\" = 'notification-indexer-app') AND $timeFilter AND time > now() - 2m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "notification-indexer-app" }
     ]
    },
    {
     "alias": "task-indexer-app",
     "measurement": "health",
     "query": "SELECT \"value\" FROM \"health\" WHERE (\"application\" = 'task-indexer-app') AND $timeFilter AND time > now() - 2m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "task-indexer-app" }
     ]
    },
    {
     "alias": "task-service-app",
     "measurement": "health",
     "query": "SELECT \"value\" FROM \"health\" WHERE (\"application\" = 'task-service-app') AND $timeFilter AND time > now() - 2m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "task-service-app" }
     ]
    },
    {
     "alias": "notification-service-app",
     "measurement": "health",
     "query": "SELECT \"value\" FROM \"health\" WHERE (\"application\" = 'notification-service-app') AND $timeFilter AND time > now() - 2m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "notification-service-app" }
     ]
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 13 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "redis",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Redis clients and connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "redis",
     "select": [
      [
       { "params": [ "clients" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "redis",
     "select": [
      [
       { "params": [ "blocked_clients" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "redis",
     "select": [
      [
       { "params": [ "rejected_connections" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Redis hits and misses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "redis",
     "select": [
      [
       { "params": [ "keyspace_hitrate" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "redis",
     "select": [
      [
       { "params": [ "keyspace_hits" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "redis",
     "select": [
      [
       { "params": [ "keyspace_misses" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Redis used memory",
   "type": "singlestat",
   "description": "Number of keys",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "redis",
     "select": [
      [
       { "params": [ "used_memory" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Redis keys",
   "type": "singlestat",
   "description": "Number of keys",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "redis_keyspace",
     "select": [
      [
       { "params": [ "keys" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Elasticsearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Elasticsearch Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 20 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       { "params": [ "uptime_in_millis" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Elasticsearch Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       { "params": [ "mem_heap_used_percent" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "elasticsearch_process",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "elasticsearch_fs",
     "select": [
      [
       {
        "params": [
         "least_usage_estimate_used_disk_percent"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ES Heap Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       { "params": [ "mem_heap_used_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ES CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "elasticsearch_process",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indexed documents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "docs_count" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}